name: flutter_application_1
description: "iFound: A Gamified Lost & Found with Map Integration."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# --- DEPENDENCIES ---
dependencies:
  flutter:
    sdk: flutter

  # Firebase Core Services
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.2.0

  # UI/UX & Utilities
  provider: ^6.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

  # Map & Geolocation
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geojson: ^1.0.0
  latlong2: ^0.8.2

# --- DEV DEPENDENCIES ---
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# --- FLUTTER SETTINGS ---
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map/